# Generated by Django 3.2.9 on 2022-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_wheather',
            fields=[
                ('city', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('forcastday', models.SmallIntegerField()),
                ('today', models.SmallIntegerField()),
                ('day_1', models.SmallIntegerField()),
                ('day_2', models.SmallIntegerField()),
                ('day_3', models.SmallIntegerField()),
                ('day_4', models.SmallIntegerField()),
                ('day_5', models.SmallIntegerField()),
                ('day_6', models.SmallIntegerField()),
                ('day_7', models.SmallIntegerField()),
            ],
        ),
    ]
